
export type param_t = 'variable' | 'flag' | 'number' | 'controller' | 'string' | 'inventory-item' | 'room-object' | 'message' | 'word';

export interface Command {
  name: string;
  code: number;
  params?: param_t[] | 'vararg';
}

const testCommands: Command[] = [
  {code:0x01, name:'equaln', params:['variable', 'number']},
  {code:0x02, name:'equalv', params:['variable', 'variable']},
  {code:0x03, name:'lessn', params:['variable', 'number']},
  {code:0x04, name:'lessv', params:['variable', 'variable']},
  {code:0x05, name:'greatern', params:['variable', 'number']},	 
  {code:0x06, name:'greaterv', params:['variable', 'variable']},
  {code:0x07, name:'isset', params:['flag']},
  {code:0x08, name:'issetv', params:['variable']},
  {code:0x09, name:'has', params:['inventory-item']},
  {code:0x0A, name:'obj.in.room', params:['inventory-item', 'variable']},
  {code:0x0B, name:'posn', params:['room-object', 'number', 'number', 'number', 'number']},
  {code:0x0C, name:'controller', params:['controller']},
  {code:0x0D, name:'have.key'},
  {code:0x0E, name:'said', params:'vararg'},
  {code:0x0F, name:'compare.strings', params:['string', 'string']},
  {code:0x10, name:'obj.in.box', params:['room-object', 'number', 'number', 'number', 'number']},
  {code:0x11, name:'center.posn', params:['room-object', 'number', 'number', 'number', 'number']},
  {code:0x12, name:'right.posn', params:['room-object', 'number', 'number', 'number', 'number']},
];

export const testCommandsByName = new Map<string, Command>(testCommands.map(v => [v.name, v]));
export const testCommandsByCode = new Map<number, Command>(testCommands.map(v => [v.code, v]));

const actionCommands: Command[] = [
  {code:0x00, name:'return'},
  {code:0x01, name:'increment', params:['variable']},
  {code:0x02, name:'decrement', params:['variable']},
  {code:0x03, name:'assignn', params:['variable','number']},
  {code:0x04, name:'assignv', params:['variable','variable']},
  {code:0x05, name:'addn', params:['variable','number']},
  {code:0x06, name:'addv', params:['variable','variable']},
  {code:0x07, name:'subn', params:['variable','number']},
  {code:0x08, name:'subv', params:['variable','variable']},
  {code:0x09, name:'lindirectv', params:['variable','variable']},
  {code:0x0A, name:'rindirect', params:['variable','variable']},
  {code:0x0B, name:'lindirectn', params:['variable','number']},
  {code:0x0C, name:'set', params:['flag']},
  {code:0x0D, name:'reset', params:['flag']},
  {code:0x0E, name:'toggle', params:['flag']},
  {code:0x0F, name:'set.v', params:['variable']},
  {code:0x10, name:'reset.v', params:['variable']},
  {code:0x11, name:'toggle.v', params:['variable']},
  {code:0x12, name:'new.room', params:['number']},
  {code:0x13, name:'new.room.v', params:['variable']},
  {code:0x14, name:'load.logics', params:['number']},
  {code:0x15, name:'load.logics.v', params:['variable']},
  {code:0x16, name:'call', params:['number']},
  {code:0x17, name:'call.v', params:['variable']},
  {code:0x18, name:'load.pic', params:['variable']},
  {code:0x19, name:'draw.pic', params:['variable']},
  {code:0x1A, name:'show.pic'},
  {code:0x1B, name:'discard.pic', params:['variable']},
  {code:0x1C, name:'overlay.pic', params:['variable']},
  {code:0x1D, name:'show.pri.screen'},
  {code:0x1E, name:'load.view', params:['number']},
  {code:0x1F, name:'load.view.v', params:['variable']},
  {code:0x20, name:'discard.view', params:['number']},
  {code:0x21, name:'animate.obj', params:['room-object']},
  {code:0x22, name:'unanimate.all'},
  {code:0x23, name:'draw', params:['room-object']},
  {code:0x24, name:'erase', params:['room-object']},
  {code:0x25, name:'position', params:['room-object','number','number']},
  {code:0x26, name:'position.v', params:['room-object','variable','variable']},
  {code:0x27, name:'get.posn', params:['room-object','variable','variable']},
  {code:0x28, name:'reposition', params:['room-object','variable','variable']},
  {code:0x29, name:'set.view', params:['room-object','number']},
  {code:0x2A, name:'set.view.v', params:['room-object','variable']},
  {code:0x2B, name:'set.loop', params:['room-object','number']},
  {code:0x2C, name:'set.loop.v', params:['room-object','variable']},
  {code:0x2D, name:'fix.loop', params:['room-object']},
  {code:0x2E, name:'release.loop', params:['room-object']},
  {code:0x2F, name:'set.cel', params:['room-object','number']},
  {code:0x30, name:'set.cel.v', params:['room-object','variable']},
  {code:0x31, name:'last.cel', params:['room-object','variable']},
  {code:0x32, name:'current.cel', params:['room-object','variable']},
  {code:0x33, name:'current.loop', params:['room-object','variable']},
  {code:0x34, name:'current.view', params:['room-object','variable']},
  {code:0x35, name:'number.of.loops', params:['room-object','variable']},
  {code:0x36, name:'set.priority', params:['room-object','number']},
  {code:0x37, name:'set.priority.v', params:['room-object','variable']},
  {code:0x38, name:'release.priority', params:['room-object']},
  {code:0x39, name:'get.priority', params:['room-object','variable']},
  {code:0x3A, name:'stop.update', params:['room-object']},
  {code:0x3B, name:'start.update', params:['room-object']},
  {code:0x3C, name:'force.update', params:['room-object']},
  {code:0x3D, name:'ignore.horizon', params:['room-object']},
  {code:0x3E, name:'observe.horizon', params:['room-object']},
  {code:0x3F, name:'set.horizon', params:['number']},
  {code:0x40, name:'object.on.water', params:['room-object']},
  {code:0x41, name:'object.on.land', params:['room-object']},
  {code:0x42, name:'object.on.anything', params:['room-object']},
  {code:0x43, name:'ignore.objs', params:['room-object']},
  {code:0x44, name:'observe.objs', params:['room-object']},
  {code:0x45, name:'distance', params:['room-object','room-object','variable']},
  {code:0x46, name:'stop.cycling', params:['room-object']},
  {code:0x47, name:'start.cycling', params:['room-object']},
  {code:0x48, name:'normal.cycle', params:['room-object']},
  {code:0x49, name:'end.of.loop', params:['room-object','flag']},
  {code:0x4A, name:'reverse.cycle', params:['room-object']},
  {code:0x4B, name:'reverse.loop', params:['room-object','flag']},
  {code:0x4C, name:'cycle.time', params:['room-object','variable']},
  {code:0x4D, name:'stop.motion', params:['room-object']},
  {code:0x4E, name:'start.motion', params:['room-object']},
  {code:0x4F, name:'step.size', params:['room-object','variable']},
  {code:0x50, name:'step.time', params:['room-object','variable']},
  {code:0x51, name:'move.obj', params:['room-object','number','number','number','flag']},
  {code:0x52, name:'move.obj.v', params:['room-object','variable','variable','variable','flag']},
  {code:0x53, name:'follow.ego', params:['room-object','number','flag']},
  {code:0x54, name:'wander', params:['room-object']},
  {code:0x55, name:'normal.motion', params:['room-object']},
  {code:0x56, name:'set.dir', params:['room-object','variable']},
  {code:0x57, name:'get.dir', params:['room-object','variable']},
  {code:0x58, name:'ignore.blocks', params:['room-object']},
  {code:0x59, name:'observe.blocks', params:['room-object']},
  {code:0x5A, name:'block', params:['number','number','number','number']},
  {code:0x5B, name:'unblock'},
  {code:0x5C, name:'get', params:['inventory-item']},
  {code:0x5D, name:'get.v', params:['variable']},
  {code:0x5E, name:'drop', params:['inventory-item']},
  {code:0x5F, name:'put', params:['inventory-item']},
  {code:0x60, name:'put.v', params:['variable','variable']},
  {code:0x61, name:'get.room.v', params:['variable','variable']},
  {code:0x62, name:'load.sound', params:['number']},
  {code:0x63, name:'sound', params:['number','flag']},
  {code:0x64, name:'stop.sound'},
  {code:0x65, name:'print', params:['message']},
  {code:0x66, name:'print.v', params:['variable']},
  {code:0x67, name:'display', params:['number','number','message']},
  {code:0x68, name:'display.v', params:['variable','variable','variable']},
  {code:0x69, name:'clear.lines', params:['number','number','message']},
  {code:0x6A, name:'text.screen'},
  {code:0x6B, name:'graphics'},
  {code:0x6C, name:'set.cursor.char', params:['message']},
  {code:0x6D, name:'set.text.attribute', params:['number','number']},
  {code:0x6E, name:'shake.screen', params:['number']},
  {code:0x6F, name:'configure.screen', params:['number','number','number']},
  {code:0x70, name:'status.line.on'},
  {code:0x71, name:'status.line.off'},
  {code:0x72, name:'set.string', params:['string','message']},
  {code:0x73, name:'get.string', params:['string','message']},
  {code:0x74, name:'word.to.string', params:['word','string']},
  {code:0x75, name:'parse', params:['string']},
  {code:0x76, name:'get.num', params:['message','variable']},
  {code:0x77, name:'prevent.input'},
  {code:0x78, name:'accept.input'},
  {code:0x79, name:'set.key', params:['number','number','number']},
  {code:0x7A, name:'add.to.pic', params:['number','number','number','number','number','number','number']},
  {code:0x7B, name:'add.to.pic.v', params:['variable','variable','variable','variable','variable','variable','variable']},
  {code:0x7C, name:'status'},
  {code:0x7D, name:'save.game'},
  {code:0x7E, name:'restore.game'},
  {code:0x7F, name:'init.disk'},
  {code:0x80, name:'restart.game'},
  {code:0x81, name:'show.obj', params:['number']},
  {code:0x82, name:'random', params:['number','number','variable']},
  {code:0x83, name:'program.control'},
  {code:0x84, name:'player.control'},
  {code:0x85, name:'obj.status.v', params:['variable']},
  {code:0x86, name:'quit', params:['number']},
  {code:0x87, name:'show.mem'},
  {code:0x88, name:'pause'},
  {code:0x89, name:'echo.line'},
  {code:0x8A, name:'cancel.line'},
  {code:0x8B, name:'init.joy'},
  {code:0x8C, name:'toggle.monitor'},
  {code:0x8D, name:'version'},
  {code:0x8E, name:'script.size', params:['number']},
  {code:0x8F, name:'set.game.id', params:['message']},
  {code:0x90, name:'log', params:['message']},
  {code:0x91, name:'set.scan.start'},
  {code:0x92, name:'reset.scan.start'},
  {code:0x93, name:'reposition.to', params:['room-object','number','number']},
  {code:0x94, name:'reposition.to.v', params:['room-object','variable','variable']},
  {code:0x95, name:'trace.on'},
  {code:0x96, name:'trace.info', params:['number','number','number']},
  {code:0x97, name:'print.at', params:['message','number','number','number']},
  {code:0x98, name:'print.at.v', params:['variable','number','number','number']},
  {code:0x99, name:'discard.view.v', params:['variable']},
  {code:0x9A, name:'clear.text.rect', params:['number','number','number','number','number']},
  {code:0x9B, name:'set.upper.left', params:['number','number']},
  {code:0x9C, name:'set.menu', params:['message']},
  {code:0x9D, name:'set.menu.item', params:['message','controller']}, // member rather than item in ScummVM docs
  {code:0x9E, name:'submit.menu'},
  {code:0x9F, name:'enable.item', params:['controller']}, // member rather than item in ScummVM docs
  {code:0xA0, name:'disable.item', params:['controller']}, // member rather than item in ScummVM docs
  {code:0xA1, name:'menu.input'},
  {code:0xA2, name:'show.obj.v', params:['variable']},
  {code:0xA3, name:'open.dialogue'},
  {code:0xA4, name:'close.dialogue'},
  {code:0xA5, name:'mul.n', params:['variable','number']},
  {code:0xA6, name:'mul.v', params:['variable','variable']},
  {code:0xA7, name:'div.n', params:['variable','number']},
  {code:0xA8, name:'div.v', params:['variable','variable']},
  {code:0xA9, name:'close.window'},
  //{code:0xAA, name:'set.simple', params:['???']},
  {code:0xAB, name:'push.script'},
  {code:0xAC, name:'pop.script'},
  {code:0xAD, name:'hold.key'},
  {code:0xAE, name:'set.pri.base', params:['number']},
  {code:0xAF, name:'discard.sound', params:['number']},
  //{code:0xB0, name:'hide.mouse', params:['|1']},
  //{code:0xB1, name:'allow.menu', params:['???']},
  {code:0xB2, name:'show.mouse'},
  {code:0xB3, name:'fence.mouse', params:['number','number','number','number']},
  {code:0xB4, name:'mouse.posn', params:['variable','variable']},
  {code:0xB5, name:'release.key'},
  {code:0xB6, name:'adj.ego.move.to.xy'},
];

export const actionCommandsByName = new Map<string, Command>(actionCommands.map(v => [v.name, v]));
export const actionCommandsByCode = new Map<number, Command>(actionCommands.map(v => [v.code, v]));
